on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Push changes
      run: |
        echo github.event
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git remote set-url origin https://github.com/$GITHUB_REPOSITORY
        git remote -v
        git tag v1.9
        git push origin v1.9
        echo "testing branch protection"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
