name: My Workflow

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'staging'
      commit-message:
        description: 'Commit message'
        required: true
        default: 'email-fn'
  push:
    branches: 
      - main
      - staging
      - develop

jobs:
  my-job:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      - name: email-step
        if: contains(github.event.head_commit.message, 'email-fn') || contains(github.event.inputs.commit-message, 'email-fn')
        run: echo 'Hello, email-fn!'
      - name: push-step
        if: contains(github.event.head_commit.message, 'push-fn') && contains(github.ref, 'develop') || contains(github.event.inputs.commit-message, 'push-fn')
        run: echo 'Hello, push-fn!'
      - name: redis-step
        if: contains(github.event.head_commit.message, 'redis-fn')  || contains(github.event.inputs.commit-message, 'redis-fn')
        run: echo 'Hello, redis-fn!'
      - name: sms-step
        if: contains(github.event.head_commit.message, 'sms-fn') && contains(github.ref, 'develop')
        run: echo 'Hello, sms-fn!'
   
  my-job1:
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest
    steps:
      - name: email-step
        if: contains(github.event.head_commit.message, 'email-fn') && contains(github.ref, 'staging') || contains(github.event.inputs.commit-message, 'email-fn')
        run: echo 'Hello, email-fn!'
      - name: push-step
        if: contains(github.event.head_commit.message, 'push-fn') && contains(github.ref, 'staging') || contains(github.event.inputs.commit-message, 'push-fn')
        run: echo 'Hello, push-fn!'
      - name: redis-step
        if: contains(github.event.head_commit.message, 'redis-fn') && contains(github.ref, 'staging') || contains(github.event.inputs.commit-message, 'redis-fn')
        run: echo 'Hello, redis-fn!'
      - name: sms-step
        if: contains(github.event.head_commit.message, 'sms-fn') && contains(github.ref, 'staging')
        run: echo 'Hello, sms-fn!'
  
  my-job2:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: email-step
        if: contains(github.event.head_commit.message, 'email-fn') && contains(github.ref, 'main') || contains(github.event.inputs.commit-message, 'email-fn')
        run: echo 'Hello, email-fn!'
      - name: push-step
        if: contains(github.event.head_commit.message, 'push-fn') && contains(github.ref, 'main') || contains(github.event.inputs.commit-message, 'push-fn')
        run: echo 'Hello, push-fn!'
      - name: redis-step
        if: contains(github.event.head_commit.message, 'redis-fn') && contains(github.ref, 'staging') || contains(github.event.inputs.commit-message, 'redis-fn')
        run: echo 'Hello, redis-fn!'
      - name: sms-step
        if: contains(github.event.head_commit.message, 'sms-fn') && contains(github.ref, 'staging')
        run: echo 'Hello, sms-fn!'
